name: Arduino Build

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 0.35.3

      - name: Install ESP32 core and libraries
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli lib install "arduinoFFT" "ESP32Servo" "LiquidCrystal_I2C"

      - name: Compile firmware sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 ${{ github.workspace }}/firmware/firmware.ino
